-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\singene\Sine_HDL_Optimized.vhd
-- Created: 2022-05-10 10:50:10
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sine_HDL_Optimized
-- Source Path: singene/singen/Sine HDL Optimized
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.singen_pac.ALL;

ENTITY Sine_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        x                                 :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
        );
END Sine_HDL_Optimized;


ARCHITECTURE rtl OF Sine_HDL_Optimized IS

  -- Constants
  CONSTANT Look_Up_Table_data             : vector_of_signed25(0 TO 511) := 
    (to_signed(16#0000000#, 25), to_signed(16#00064BA#, 25), to_signed(16#000C974#, 25),
     to_signed(16#0012E2E#, 25), to_signed(16#00192E7#, 25), to_signed(16#001F79E#, 25),
     to_signed(16#0025C55#, 25), to_signed(16#002C10A#, 25), to_signed(16#00325BE#, 25),
     to_signed(16#0038A6F#, 25), to_signed(16#003EF1E#, 25), to_signed(16#00453CB#, 25),
     to_signed(16#004B875#, 25), to_signed(16#0051D1D#, 25), to_signed(16#00581C1#, 25),
     to_signed(16#005E661#, 25), to_signed(16#0064AFE#, 25), to_signed(16#006AF97#, 25),
     to_signed(16#007142C#, 25), to_signed(16#00778BD#, 25), to_signed(16#007DD49#, 25),
     to_signed(16#00841D0#, 25), to_signed(16#008A652#, 25), to_signed(16#0090ACF#, 25),
     to_signed(16#0096F46#, 25), to_signed(16#009D3B7#, 25), to_signed(16#00A3822#, 25),
     to_signed(16#00A9C87#, 25), to_signed(16#00B00E5#, 25), to_signed(16#00B653C#, 25),
     to_signed(16#00BC98D#, 25), to_signed(16#00C2DD6#, 25), to_signed(16#00C9217#, 25),
     to_signed(16#00CF651#, 25), to_signed(16#00D5A83#, 25), to_signed(16#00DBEAC#, 25),
     to_signed(16#00E22CD#, 25), to_signed(16#00E86E5#, 25), to_signed(16#00EEAF4#, 25),
     to_signed(16#00F4EFA#, 25), to_signed(16#00FB2F7#, 25), to_signed(16#01016E9#, 25),
     to_signed(16#0107AD2#, 25), to_signed(16#010DEB1#, 25), to_signed(16#0114285#, 25),
     to_signed(16#011A64E#, 25), to_signed(16#0120A0C#, 25), to_signed(16#0126DC0#, 25),
     to_signed(16#012D168#, 25), to_signed(16#0133504#, 25), to_signed(16#0139894#, 25),
     to_signed(16#013FC18#, 25), to_signed(16#0145F90#, 25), to_signed(16#014C2FC#, 25),
     to_signed(16#015265A#, 25), to_signed(16#01589AB#, 25), to_signed(16#015ECEF#, 25),
     to_signed(16#0165025#, 25), to_signed(16#016B34E#, 25), to_signed(16#0171668#, 25),
     to_signed(16#0177975#, 25), to_signed(16#017DC72#, 25), to_signed(16#0183F61#, 25),
     to_signed(16#018A241#, 25), to_signed(16#0190511#, 25), to_signed(16#01967D3#, 25),
     to_signed(16#019CA84#, 25), to_signed(16#01A2D25#, 25), to_signed(16#01A8FB6#, 25),
     to_signed(16#01AF237#, 25), to_signed(16#01B54A7#, 25), to_signed(16#01BB706#, 25),
     to_signed(16#01C1954#, 25), to_signed(16#01C7B91#, 25), to_signed(16#01CDDBC#, 25),
     to_signed(16#01D3FD5#, 25), to_signed(16#01DA1DC#, 25), to_signed(16#01E03D0#, 25),
     to_signed(16#01E65B2#, 25), to_signed(16#01EC782#, 25), to_signed(16#01F293E#, 25),
     to_signed(16#01F8AE6#, 25), to_signed(16#01FEC7C#, 25), to_signed(16#0204DFD#, 25),
     to_signed(16#020AF6B#, 25), to_signed(16#02110C4#, 25), to_signed(16#0217209#, 25),
     to_signed(16#021D339#, 25), to_signed(16#0223454#, 25), to_signed(16#022955A#, 25),
     to_signed(16#022F64A#, 25), to_signed(16#0235725#, 25), to_signed(16#023B7EA#, 25),
     to_signed(16#0241899#, 25), to_signed(16#0247932#, 25), to_signed(16#024D9B4#, 25),
     to_signed(16#0253A1F#, 25), to_signed(16#0259A73#, 25), to_signed(16#025FAB0#, 25),
     to_signed(16#0265AD5#, 25), to_signed(16#026BAE2#, 25), to_signed(16#0271AD8#, 25),
     to_signed(16#0277AB5#, 25), to_signed(16#027DA7A#, 25), to_signed(16#0283A26#, 25),
     to_signed(16#02899B9#, 25), to_signed(16#028F933#, 25), to_signed(16#0295894#, 25),
     to_signed(16#029B7DB#, 25), to_signed(16#02A1709#, 25), to_signed(16#02A761C#, 25),
     to_signed(16#02AD515#, 25), to_signed(16#02B33F3#, 25), to_signed(16#02B92B7#, 25),
     to_signed(16#02BF160#, 25), to_signed(16#02C4FED#, 25), to_signed(16#02CAE5F#, 25),
     to_signed(16#02D0CB6#, 25), to_signed(16#02D6AF0#, 25), to_signed(16#02DC90E#, 25),
     to_signed(16#02E2710#, 25), to_signed(16#02E84F6#, 25), to_signed(16#02EE2BE#, 25),
     to_signed(16#02F406A#, 25), to_signed(16#02F9DF8#, 25), to_signed(16#02FFB69#, 25),
     to_signed(16#03058BC#, 25), to_signed(16#030B5F1#, 25), to_signed(16#0311308#, 25),
     to_signed(16#0317001#, 25), to_signed(16#031CCDB#, 25), to_signed(16#0322996#, 25),
     to_signed(16#0328632#, 25), to_signed(16#032E2AF#, 25), to_signed(16#0333F0C#, 25),
     to_signed(16#0339B4A#, 25), to_signed(16#033F767#, 25), to_signed(16#0345365#, 25),
     to_signed(16#034AF42#, 25), to_signed(16#0350AFE#, 25), to_signed(16#035669A#, 25),
     to_signed(16#035C214#, 25), to_signed(16#0361D6D#, 25), to_signed(16#03678A5#, 25),
     to_signed(16#036D3BB#, 25), to_signed(16#0372EAF#, 25), to_signed(16#0378981#, 25),
     to_signed(16#037E430#, 25), to_signed(16#0383EBD#, 25), to_signed(16#0389927#, 25),
     to_signed(16#038F36E#, 25), to_signed(16#0394D91#, 25), to_signed(16#039A792#, 25),
     to_signed(16#03A016E#, 25), to_signed(16#03A5B27#, 25), to_signed(16#03AB4BB#, 25),
     to_signed(16#03B0E2B#, 25), to_signed(16#03B6776#, 25), to_signed(16#03BC09D#, 25),
     to_signed(16#03C199F#, 25), to_signed(16#03C727B#, 25), to_signed(16#03CCB32#, 25),
     to_signed(16#03D23C4#, 25), to_signed(16#03D7C2F#, 25), to_signed(16#03DD475#, 25),
     to_signed(16#03E2C94#, 25), to_signed(16#03E848D#, 25), to_signed(16#03EDC5F#, 25),
     to_signed(16#03F340A#, 25), to_signed(16#03F8B8D#, 25), to_signed(16#03FE2EA#, 25),
     to_signed(16#0403A1F#, 25), to_signed(16#040912C#, 25), to_signed(16#040E811#, 25),
     to_signed(16#0413ECE#, 25), to_signed(16#0419563#, 25), to_signed(16#041EBCF#, 25),
     to_signed(16#0424212#, 25), to_signed(16#042982C#, 25), to_signed(16#042EE1D#, 25),
     to_signed(16#04343E5#, 25), to_signed(16#0439982#, 25), to_signed(16#043EEF6#, 25),
     to_signed(16#0444440#, 25), to_signed(16#0449960#, 25), to_signed(16#044EE55#, 25),
     to_signed(16#045431F#, 25), to_signed(16#04597BF#, 25), to_signed(16#045EC33#, 25),
     to_signed(16#046407C#, 25), to_signed(16#046949A#, 25), to_signed(16#046E88C#, 25),
     to_signed(16#0473C52#, 25), to_signed(16#0478FEC#, 25), to_signed(16#047E359#, 25),
     to_signed(16#048369B#, 25), to_signed(16#04889AF#, 25), to_signed(16#048DC96#, 25),
     to_signed(16#0492F51#, 25), to_signed(16#04981DE#, 25), to_signed(16#049D43D#, 25),
     to_signed(16#04A266F#, 25), to_signed(16#04A7873#, 25), to_signed(16#04ACA48#, 25),
     to_signed(16#04B1BF0#, 25), to_signed(16#04B6D69#, 25), to_signed(16#04BBEB3#, 25),
     to_signed(16#04C0FCE#, 25), to_signed(16#04C60BA#, 25), to_signed(16#04CB177#, 25),
     to_signed(16#04D0204#, 25), to_signed(16#04D5262#, 25), to_signed(16#04DA290#, 25),
     to_signed(16#04DF28E#, 25), to_signed(16#04E425B#, 25), to_signed(16#04E91F8#, 25),
     to_signed(16#04EE164#, 25), to_signed(16#04F30A0#, 25), to_signed(16#04F7FAA#, 25),
     to_signed(16#04FCE84#, 25), to_signed(16#0501D2B#, 25), to_signed(16#0506BA2#, 25),
     to_signed(16#050B9E6#, 25), to_signed(16#05107F8#, 25), to_signed(16#05155D8#, 25),
     to_signed(16#051A386#, 25), to_signed(16#051F102#, 25), to_signed(16#0523E4A#, 25),
     to_signed(16#0528B60#, 25), to_signed(16#052D842#, 25), to_signed(16#05324F1#, 25),
     to_signed(16#053716D#, 25), to_signed(16#053BDB5#, 25), to_signed(16#05409C9#, 25),
     to_signed(16#05455A9#, 25), to_signed(16#054A155#, 25), to_signed(16#054ECCD#, 25),
     to_signed(16#0553810#, 25), to_signed(16#055831E#, 25), to_signed(16#055CDF7#, 25),
     to_signed(16#056189B#, 25), to_signed(16#056630A#, 25), to_signed(16#056AD43#, 25),
     to_signed(16#056F747#, 25), to_signed(16#0574114#, 25), to_signed(16#0578AAC#, 25),
     to_signed(16#057D40D#, 25), to_signed(16#0581D38#, 25), to_signed(16#058662D#, 25),
     to_signed(16#058AEEB#, 25), to_signed(16#058F772#, 25), to_signed(16#0593FC1#, 25),
     to_signed(16#05987DA#, 25), to_signed(16#059CFBB#, 25), to_signed(16#05A1764#, 25),
     to_signed(16#05A5ED6#, 25), to_signed(16#05AA60F#, 25), to_signed(16#05AED11#, 25),
     to_signed(16#05B33DA#, 25), to_signed(16#05B7A6B#, 25), to_signed(16#05BC0C3#, 25),
     to_signed(16#05C06E2#, 25), to_signed(16#05C4CC9#, 25), to_signed(16#05C9276#, 25),
     to_signed(16#05CD7E9#, 25), to_signed(16#05D1D24#, 25), to_signed(16#05D6224#, 25),
     to_signed(16#05DA6EB#, 25), to_signed(16#05DEB78#, 25), to_signed(16#05E2FCB#, 25),
     to_signed(16#05E73E3#, 25), to_signed(16#05EB7C1#, 25), to_signed(16#05EFB64#, 25),
     to_signed(16#05F3ECC#, 25), to_signed(16#05F81FA#, 25), to_signed(16#05FC4EC#, 25),
     to_signed(16#06007A3#, 25), to_signed(16#0604A1E#, 25), to_signed(16#0608C5E#, 25),
     to_signed(16#060CE62#, 25), to_signed(16#061102A#, 25), to_signed(16#06151B6#, 25),
     to_signed(16#0619306#, 25), to_signed(16#061D419#, 25), to_signed(16#06214F0#, 25),
     to_signed(16#062558A#, 25), to_signed(16#06295E7#, 25), to_signed(16#062D607#, 25),
     to_signed(16#06315EA#, 25), to_signed(16#063558F#, 25), to_signed(16#06394F7#, 25),
     to_signed(16#063D421#, 25), to_signed(16#064130E#, 25), to_signed(16#06451BC#, 25),
     to_signed(16#064902D#, 25), to_signed(16#064CE5F#, 25), to_signed(16#0650C52#, 25),
     to_signed(16#0654A07#, 25), to_signed(16#065877E#, 25), to_signed(16#065C4B5#, 25),
     to_signed(16#06601AE#, 25), to_signed(16#0663E67#, 25), to_signed(16#0667AE1#, 25),
     to_signed(16#066B71C#, 25), to_signed(16#066F316#, 25), to_signed(16#0672ED2#, 25),
     to_signed(16#0676A4D#, 25), to_signed(16#067A588#, 25), to_signed(16#067E083#, 25),
     to_signed(16#0681B3E#, 25), to_signed(16#06855B8#, 25), to_signed(16#0688FF2#, 25),
     to_signed(16#068C9EA#, 25), to_signed(16#06903A2#, 25), to_signed(16#0693D19#, 25),
     to_signed(16#069764F#, 25), to_signed(16#069AF44#, 25), to_signed(16#069E7F7#, 25),
     to_signed(16#06A2068#, 25), to_signed(16#06A5898#, 25), to_signed(16#06A9086#, 25),
     to_signed(16#06AC831#, 25), to_signed(16#06AFF9B#, 25), to_signed(16#06B36C3#, 25),
     to_signed(16#06B6DA8#, 25), to_signed(16#06BA44A#, 25), to_signed(16#06BDAAA#, 25),
     to_signed(16#06C10C7#, 25), to_signed(16#06C46A1#, 25), to_signed(16#06C7C39#, 25),
     to_signed(16#06CB18D#, 25), to_signed(16#06CE69D#, 25), to_signed(16#06D1B6A#, 25),
     to_signed(16#06D4FF4#, 25), to_signed(16#06D843A#, 25), to_signed(16#06DB83C#, 25),
     to_signed(16#06DEBFA#, 25), to_signed(16#06E1F74#, 25), to_signed(16#06E52AA#, 25),
     to_signed(16#06E859C#, 25), to_signed(16#06EB849#, 25), to_signed(16#06EEAB2#, 25),
     to_signed(16#06F1CD5#, 25), to_signed(16#06F4EB5#, 25), to_signed(16#06F804F#, 25),
     to_signed(16#06FB1A4#, 25), to_signed(16#06FE2B4#, 25), to_signed(16#070137E#, 25),
     to_signed(16#0704404#, 25), to_signed(16#0707443#, 25), to_signed(16#070A43D#, 25),
     to_signed(16#070D3F2#, 25), to_signed(16#0710360#, 25), to_signed(16#0713289#, 25),
     to_signed(16#071616B#, 25), to_signed(16#0719007#, 25), to_signed(16#071BE5D#, 25),
     to_signed(16#071EC6C#, 25), to_signed(16#0721A35#, 25), to_signed(16#07247B7#, 25),
     to_signed(16#07274F3#, 25), to_signed(16#072A1E7#, 25), to_signed(16#072CE95#, 25),
     to_signed(16#072FAFB#, 25), to_signed(16#073271B#, 25), to_signed(16#07352F3#, 25),
     to_signed(16#0737E83#, 25), to_signed(16#073A9CC#, 25), to_signed(16#073D4CE#, 25),
     to_signed(16#073FF87#, 25), to_signed(16#07429F9#, 25), to_signed(16#0745423#, 25),
     to_signed(16#0747E05#, 25), to_signed(16#074A79E#, 25), to_signed(16#074D0F0#, 25),
     to_signed(16#074F9F9#, 25), to_signed(16#07522BA#, 25), to_signed(16#0754B32#, 25),
     to_signed(16#0757361#, 25), to_signed(16#0759B48#, 25), to_signed(16#075C2E6#, 25),
     to_signed(16#075EA3B#, 25), to_signed(16#0761147#, 25), to_signed(16#076380A#, 25),
     to_signed(16#0765E84#, 25), to_signed(16#07684B4#, 25), to_signed(16#076AA9B#, 25),
     to_signed(16#076D038#, 25), to_signed(16#076F58C#, 25), to_signed(16#0771A97#, 25),
     to_signed(16#0773F57#, 25), to_signed(16#07763CE#, 25), to_signed(16#07787FA#, 25),
     to_signed(16#077ABDD#, 25), to_signed(16#077CF76#, 25), to_signed(16#077F2C4#, 25),
     to_signed(16#07815C8#, 25), to_signed(16#0783882#, 25), to_signed(16#0785AF1#, 25),
     to_signed(16#0787D16#, 25), to_signed(16#0789EF0#, 25), to_signed(16#078C080#, 25),
     to_signed(16#078E1C4#, 25), to_signed(16#07902BE#, 25), to_signed(16#079236D#, 25),
     to_signed(16#07943D1#, 25), to_signed(16#07963EA#, 25), to_signed(16#07983B7#, 25),
     to_signed(16#079A339#, 25), to_signed(16#079C270#, 25), to_signed(16#079E15C#, 25),
     to_signed(16#079FFFC#, 25), to_signed(16#07A1E51#, 25), to_signed(16#07A3C5A#, 25),
     to_signed(16#07A5A17#, 25), to_signed(16#07A7789#, 25), to_signed(16#07A94AE#, 25),
     to_signed(16#07AB188#, 25), to_signed(16#07ACE16#, 25), to_signed(16#07AEA57#, 25),
     to_signed(16#07B064D#, 25), to_signed(16#07B21F6#, 25), to_signed(16#07B3D54#, 25),
     to_signed(16#07B5864#, 25), to_signed(16#07B7329#, 25), to_signed(16#07B8DA1#, 25),
     to_signed(16#07BA7CC#, 25), to_signed(16#07BC1AB#, 25), to_signed(16#07BDB3E#, 25),
     to_signed(16#07BF483#, 25), to_signed(16#07C0D7C#, 25), to_signed(16#07C2628#, 25),
     to_signed(16#07C3E87#, 25), to_signed(16#07C5699#, 25), to_signed(16#07C6E5E#, 25),
     to_signed(16#07C85D7#, 25), to_signed(16#07C9D02#, 25), to_signed(16#07CB3DF#, 25),
     to_signed(16#07CCA70#, 25), to_signed(16#07CE0B3#, 25), to_signed(16#07CF6A9#, 25),
     to_signed(16#07D0C52#, 25), to_signed(16#07D21AD#, 25), to_signed(16#07D36BB#, 25),
     to_signed(16#07D4B7B#, 25), to_signed(16#07D5FEE#, 25), to_signed(16#07D7413#, 25),
     to_signed(16#07D87EA#, 25), to_signed(16#07D9B73#, 25), to_signed(16#07DAEAF#, 25),
     to_signed(16#07DC19D#, 25), to_signed(16#07DD43D#, 25), to_signed(16#07DE68F#, 25),
     to_signed(16#07DF893#, 25), to_signed(16#07E0A49#, 25), to_signed(16#07E1BB1#, 25),
     to_signed(16#07E2CCB#, 25), to_signed(16#07E3D97#, 25), to_signed(16#07E4E15#, 25),
     to_signed(16#07E5E44#, 25), to_signed(16#07E6E25#, 25), to_signed(16#07E7DB8#, 25),
     to_signed(16#07E8CFD#, 25), to_signed(16#07E9BF3#, 25), to_signed(16#07EAA9B#, 25),
     to_signed(16#07EB8F4#, 25), to_signed(16#07EC6FF#, 25), to_signed(16#07ED4BB#, 25),
     to_signed(16#07EE229#, 25), to_signed(16#07EEF48#, 25), to_signed(16#07EFC19#, 25),
     to_signed(16#07F089B#, 25), to_signed(16#07F14CE#, 25), to_signed(16#07F20B3#, 25),
     to_signed(16#07F2C49#, 25), to_signed(16#07F3790#, 25), to_signed(16#07F4288#, 25),
     to_signed(16#07F4D32#, 25), to_signed(16#07F578D#, 25), to_signed(16#07F6198#, 25),
     to_signed(16#07F6B55#, 25), to_signed(16#07F74C3#, 25), to_signed(16#07F7DE3#, 25),
     to_signed(16#07F86B3#, 25), to_signed(16#07F8F34#, 25), to_signed(16#07F9766#, 25),
     to_signed(16#07F9F4A#, 25), to_signed(16#07FA6DE#, 25), to_signed(16#07FAE23#, 25),
     to_signed(16#07FB519#, 25), to_signed(16#07FBBC0#, 25), to_signed(16#07FC218#, 25),
     to_signed(16#07FC821#, 25), to_signed(16#07FCDDA#, 25), to_signed(16#07FD345#, 25),
     to_signed(16#07FD860#, 25), to_signed(16#07FDD2C#, 25), to_signed(16#07FE1A9#, 25),
     to_signed(16#07FE5D7#, 25), to_signed(16#07FE9B5#, 25), to_signed(16#07FED45#, 25),
     to_signed(16#07FF085#, 25), to_signed(16#07FF376#, 25), to_signed(16#07FF618#, 25),
     to_signed(16#07FF86A#, 25), to_signed(16#07FFA6D#, 25), to_signed(16#07FFC21#, 25),
     to_signed(16#07FFD86#, 25), to_signed(16#07FFE9B#, 25), to_signed(16#07FFF61#, 25),
     to_signed(16#07FFFD8#, 25), to_signed(16#0800000#, 25));  -- sfix25 [512]

  -- Signals
  SIGNAL u_signed                         : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL insig_out1                       : unsigned(10 DOWNTO 0);  -- ufix11_En11
  SIGNAL Point50_out1                     : unsigned(24 DOWNTO 0);  -- ufix25_En25
  SIGNAL LTEp50_1_cast                    : unsigned(24 DOWNTO 0);  -- ufix25_En25
  SIGNAL LTEp50_relop1                    : std_logic;
  SIGNAL RAMDelayBalance_out1             : std_logic;
  SIGNAL pow2switch_out1                  : std_logic;
  SIGNAL Amp50_sub_cast                   : signed(25 DOWNTO 0);  -- sfix26_En25
  SIGNAL Amp50_sub_cast_1                 : signed(25 DOWNTO 0);  -- sfix26_En25
  SIGNAL Amp50_out1                       : signed(25 DOWNTO 0);  -- sfix26_En25
  SIGNAL insig_out1_dtc                   : signed(25 DOWNTO 0);  -- sfix26_En25
  SIGNAL QuadHandle1_out1                 : signed(25 DOWNTO 0);  -- sfix26_En25
  SIGNAL Point25_out1                     : unsigned(24 DOWNTO 0);  -- ufix25_En25
  SIGNAL LTEp25_1_cast                    : signed(25 DOWNTO 0);  -- sfix26_En25
  SIGNAL LTEp25_relop1                    : std_logic;
  SIGNAL p50mA_sub_cast                   : signed(26 DOWNTO 0);  -- sfix27_En25
  SIGNAL p50mA_sub_cast_1                 : signed(26 DOWNTO 0);  -- sfix27_En25
  SIGNAL p50mA_out1                       : signed(26 DOWNTO 0);  -- sfix27_En25
  SIGNAL p50mA_out1_dtc                   : unsigned(10 DOWNTO 0);  -- ufix11_En11
  SIGNAL QuadHandle1_out1_dtc             : unsigned(10 DOWNTO 0);  -- ufix11_En11
  SIGNAL QuadHandle2_out1                 : unsigned(10 DOWNTO 0);  -- ufix11_En11
  SIGNAL CastU16En2_out1                  : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL CastU16En4_out1                  : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL CastU16En3_out1                  : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Saturation_out1                  : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Switch_out1                      : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Look_Up_Table_k                  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Look_Up_Table_out1               : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Look_Up_Table_out1_1             : signed(24 DOWNTO 0) := to_signed(16#0000000#, 25);  -- sfix25_En23
  SIGNAL Negate_cast                      : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Negate_cast_1                    : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Negate_out1                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Sine                             : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Sine_1                           : signed(24 DOWNTO 0);  -- sfix25_En23

BEGIN
  -- (C) 2016 Mathworks, Inc

  u_signed <= signed(u);

  insig_out1 <= unsigned(u_signed(22 DOWNTO 12));

  Point50_out1 <= to_unsigned(16#1000000#, 25);

  LTEp50_1_cast <= insig_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  
  LTEp50_relop1 <= '1' WHEN LTEp50_1_cast <= Point50_out1 ELSE
      '0';

  delayMatch_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        RAMDelayBalance_out1 <= '0';
      ELSIF enb = '1' THEN
        RAMDelayBalance_out1 <= LTEp50_relop1;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  pow2switch_out1 <= '1';

  Amp50_sub_cast <= signed(resize(insig_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 26));
  Amp50_sub_cast_1 <= signed(resize(Point50_out1, 26));
  Amp50_out1 <= Amp50_sub_cast - Amp50_sub_cast_1;

  insig_out1_dtc <= signed(resize(insig_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 26));

  
  QuadHandle1_out1 <= Amp50_out1 WHEN LTEp50_relop1 = '0' ELSE
      insig_out1_dtc;

  Point25_out1 <= to_unsigned(16#0800000#, 25);

  LTEp25_1_cast <= signed(resize(Point25_out1, 26));
  
  LTEp25_relop1 <= '1' WHEN QuadHandle1_out1 <= LTEp25_1_cast ELSE
      '0';

  p50mA_sub_cast <= signed(resize(Point50_out1, 27));
  p50mA_sub_cast_1 <= resize(QuadHandle1_out1, 27);
  p50mA_out1 <= p50mA_sub_cast - p50mA_sub_cast_1;

  p50mA_out1_dtc <= unsigned(p50mA_out1(24 DOWNTO 14));

  QuadHandle1_out1_dtc <= unsigned(QuadHandle1_out1(24 DOWNTO 14));

  
  QuadHandle2_out1 <= p50mA_out1_dtc WHEN LTEp25_relop1 = '0' ELSE
      QuadHandle1_out1_dtc;

  CastU16En2_out1 <= QuadHandle2_out1;

  CastU16En4_out1 <= resize(CastU16En2_out1, 12);

  
  CastU16En3_out1 <= "11111111111" WHEN CastU16En4_out1(11) /= '0' ELSE
      CastU16En4_out1(10 DOWNTO 0);

  -- saturation block maybe optimized away
  -- if the NumDataPoints is a power of 2
  
  Saturation_out1 <= to_unsigned(16#1FF#, 11) WHEN CastU16En3_out1 > to_unsigned(16#1FF#, 11) ELSE
      CastU16En3_out1;

  
  Switch_out1 <= CastU16En3_out1 WHEN pow2switch_out1 = '0' ELSE
      Saturation_out1;

  
  Look_Up_Table_k <= to_unsigned(16#000#, 9) WHEN Switch_out1 = to_unsigned(16#000#, 11) ELSE
      to_unsigned(16#1FF#, 9) WHEN Switch_out1 >= to_unsigned(16#1FF#, 11) ELSE
      Switch_out1(8 DOWNTO 0);
  Look_Up_Table_out1 <= Look_Up_Table_data(to_integer(Look_Up_Table_k));

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Look_Up_Table_out1_1 <= Look_Up_Table_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Negate_cast <= resize(Look_Up_Table_out1_1, 26);
  Negate_cast_1 <=  - (Negate_cast);
  Negate_out1 <= Negate_cast_1(24 DOWNTO 0);

  
  Sine <= Negate_out1 WHEN RAMDelayBalance_out1 = '0' ELSE
      Look_Up_Table_out1_1;

  Sine_1 <= Sine;

  x <= std_logic_vector(Sine_1);

END rtl;

