-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\singene\singen.vhd
-- Created: 2022-05-10 10:50:10
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2e-07
-- Target subsystem base rate: 2e-07
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2e-07
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- sinout                        ce_out        2e-07
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: singen
-- Source Path: singene/singen
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY singen IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        rampin                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        ce_out                            :   OUT   std_logic;
        sinout                            :   OUT   std_logic_vector(23 DOWNTO 0)  -- ufix24
        );
END singen;


ARCHITECTURE rtl OF singen IS

  -- Component Declarations
  COMPONENT Sine_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          x                               :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sine_HDL_Optimized
    USE ENTITY work.Sine_HDL_Optimized(rtl);

  -- Signals
  SIGNAL Constant1_out1                   : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Constant_out1                    : unsigned(23 DOWNTO 0);  -- ufix24_En20
  SIGNAL Sine                             : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Sine_signed                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Add_add_cast                     : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Add_add_cast_1                   : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Add_add_temp                     : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Add_out1                         : unsigned(23 DOWNTO 0);  -- ufix24_En20
  SIGNAL Product_mul_temp                 : unsigned(47 DOWNTO 0);  -- ufix48_En20
  SIGNAL Product_out1                     : unsigned(23 DOWNTO 0);  -- ufix24

BEGIN
  u_Sine_HDL_Optimized : Sine_HDL_Optimized
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => clk_enable,
              u => rampin,  -- sfix24_En23
              x => Sine  -- sfix25_En23
              );

  Constant1_out1 <= to_unsigned(16#0003E8#, 24);

  Constant_out1 <= to_unsigned(16#100000#, 24);

  Sine_signed <= signed(Sine);

  Add_add_cast <= signed(resize(Constant_out1 & '0' & '0' & '0', 29));
  Add_add_cast_1 <= resize(Sine_signed, 29);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  Add_out1 <= unsigned(Add_add_temp(26 DOWNTO 3));

  Product_mul_temp <= Constant1_out1 * Add_out1;
  Product_out1 <= Product_mul_temp(43 DOWNTO 20);

  sinout <= std_logic_vector(Product_out1);

  ce_out <= clk_enable;

END rtl;

