# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.cache/wt [current_project]
set_property parent.project_path C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/ADAU1761_interface.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/Complex4Multiply.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/Complex4Multiply_block.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/Complex4Multiply_block1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/Complex4Multiply_block2.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/FFT_block_pac.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SimpleDualPortRAM_generic.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF1_1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_2.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator2.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF2_2.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/TWDLROM_3_1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_3.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator3.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF1_3.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_4.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator4.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF2_4.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/TWDLROM_5_1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_5.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator5.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF1_5.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_6.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator6.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF2_6.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/TWDLROM_7_1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_7.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator7.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF1_7.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_8.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator8.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF2_8.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/TWDLROM_9_1.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_CTRL1_1_block.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/SDFCommutator9.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX22FFT_SDF1_9.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/RADIX2FFT_bitNatural.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/FFT_HDL_Optimized.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/FFTblock/FFT_block.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/singen_pac.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/Sine_HDL_Optimized.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/peakfinder.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/adau1761_configuraiton_data.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/adau1761_izedboard.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/ascii_rom.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/audio_top.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/clocking.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/delay.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/i2c.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/i2s_data_interface.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/i3c2.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/oled_ctrl.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/oled_ex.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/oled_init.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/new/sawtooth_gen.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/singen.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/spi_ctrl.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/new/tuningcalculator.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/imports/allcode/upper.vhd
  C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/sources_1/imports/sources_1/new/Toplayer.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/constrs_1/imports/constraints/zed_audio.xdc
set_property used_in_implementation false [get_files C:/Users/there/Downloads/Fullcode_with_simlink_FFT_FINAL/Fullcode_with_simlink_FFT_FINAL.srcs/constrs_1/imports/constraints/zed_audio.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Toplayer -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Toplayer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Toplayer_utilization_synth.rpt -pb Toplayer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
